### ISSUE TITLE
Calendar refresh

### ISSUE THREAD

**Issue by AndriiDidkivsky** [jsmodules/angular-material-calendar#100]
How  can I refresh calendar after new data were provided. Could I organize Something like two way data binding ? Calendar are rendering aging only after prev next buttons were triggered.

**Comment by djleonskennedy** [comment]
Also have issue with it. Can't refresh calendar if data have changed, seems like it's bug with compiling of a template

**Comment by AndriiDidkivsky** [comment]
Resolved with service MaterialCalendarData. 
Service contains calendar current  data and methods to work with.
Please add this into documentation that data can be updated with this service.
