### ISSUE TITLE
It is working with angular v1.5.8 ?

### ISSUE THREAD

**Issue by MauricioC31** [jsmodules/angular-material-calendar#112]
Hi Everyone; my question is if this is working with angular v1.5.8 ?

**Comment by egunsoma** [comment]
It works with 1.6.x for me.

**Comment by MauricioC31** [comment]
My problem is when inicialize the module ''materialCalendar'', for example:

angular.module('juridico', ['ngRoute', 'ngMaterial', 'ngMdIcons', 'ngMessages', 'materialCalendar' ])

the error in app is:

![image](https://cloud.githubusercontent.com/assets/9923465/24401981/004c1178-138d-11e7-807c-eac68deb1edd.png).

Thanks for the help.

**Comment by egunsoma** [comment]
hmm its strange, could you make sure if you including **all** the JS files for the given modules?

Other question: if you remove only the *materialCalendar* module, everything works as expected?

**Comment by MauricioC31** [comment]
Yes is strange. I´m include all JS files in the index for the modules and yes when remove only materialCalendar it is work OK.
=(
Thanks for the help.

**Comment by MauricioC31** [comment]
The solution are that ng-sanitize not was include in my project.

Thanks for the support.
