### ISSUE TITLE
Localization advise

### ISSUE THREAD

**Issue by Loksly** [jsmodules/angular-material-calendar#39]
Hi!

I'd just like to notice it would be fine to advise everyone that wants to use a different locale for the calendar, they only need to use the correct angular-i18n file.

Two different ways to install:
```bash
bower install angular-i18n
```
or
```bash
npm install angular-i18n
```
then use the script tag to include the translations (for example, for spanish locale):
```html
<script src="bower_components/angular-i18n/angular-locale_es-es.js"></script>
```
or you may use a CDN like cdnjs:

https://cdnjs.com/libraries/angular-i18n

Please consider including some related information at README.md

Have a nice day

**Comment by bradberger** [comment]
Good point, this isn't actually the first time the question has been brought up (#29), so we definitely need to add documentation for that. 

I'll add it to the to-do list for the next release. It's up for grabs if anyone wants to update the documentation, if not when I get a free moment I'll try to get to it.
