### ISSUE TITLE
Binding data to a date.

### ISSUE THREAD

**Issue by saturday** [jsmodules/angular-material-calendar#42]
Right now, the only way to associate external data with a specific day in the calendar is via setDayContent(), and this is mostly presentational. I didn't see anything in the demo that indicates that it's possible to do what I'm suggesting. Is this feature in the pipeline?

Edit: Also, is there an existing, preferred hack that makes this possible?

**Comment by saturday** [comment]
What I ended up doing, since in this case, the date provides me with a psuedo-foreign key to the record in question, I'm able to loop through the scope events in question and do a match based on the date returned via the dayClick function. It's not ideal by any means, but it works for me use case.

**Comment by gavinbarron** [comment]
Could you explain what it is that you're looking to do?

**Comment by gavinbarron** [comment]
Closing, feel free to re-open if necessary
