### ISSUE TITLE
reload data

### ISSUE THREAD

**Issue by reyazucar** [jsmodules/angular-material-calendar#43]
Hi, is possible to reload all the calendar component after it was rendered?
thanks in advance

**Comment by gavinbarron** [comment]
Yes.

Inject the MaterialCalendarData service into the component where you're looking to re-load the data. Then after you get your new data set loop through calling the MaterialCalendarData.setDayContent(date,content) function to update the content for each of the dates in your new data set. 
If you have deletions that you need to perform then you'll need to ensure the component still has a copy of the previously loaded data set to work out your delete set and just update those dates with an empty string.
