### ISSUE TITLE
Calendar is not auto-updating when new event is being created.

### ISSUE THREAD

**Issue by KingstonPla** [jsmodules/angular-material-calendar#55]
How can I refresh / reload calendar when I update setDayContent? 

 self.diary.setDayContent = function(date) {   

            var deferred = $q.defer();
            $timeout(function () {
                var ReminderNum = 0;
                var reminderPromise = ReminderAPI.get({ userID: UserID, RosterDate: date }).$promise.then(function (reminders) {
                    angular.forEach(reminders, function (val, key) {    
                        ReminderNum++;
                    });
                    var promise = RosterAPI.daily({ userID: UserID, daily: date }).$promise.then(function (rosters) {
                        var workTime = "<p></p>";
                        var displayRoster = [];
                        var reminderTxtNum = '';
                        
                        if (ReminderNum > 1) {
                            reminderTxtNum = "<p><i class=\"fa fa-bell-o\"></i> You have " + ReminderNum + " reminders.</p>";
                        }
                        if (ReminderNum == 1) {
                            reminderTxtNum = "<p><i class=\"fa fa-bell-o\"></i> You have " + ReminderNum + " reminder.</p>";
                        }

                        angular.forEach(rosters, function (val, key) {
                            if (angular.equals(val.RosterDate, date)) {
                                var startTime = val.StartTime;
                                var endTime = val.EndTime;

                                val.StartTime.split(':').map(Number).reduce(function (pUnit, cUnit, index) {
                                    if (cUnit == 0) cUnit = '00';
                                    if (index == 1) startTime = pUnit + ':' + cUnit + 'am';
                                });
                                val.EndTime.split(':').map(Number).reduce(function (pUnit, cUnit, index) {
                                    if (cUnit == 0) cUnit = '00';
                                    if (index == 1) endTime = pUnit + ':' + cUnit + 'pm';
                                });

                                workTime = "<p>" + startTime + " - " + endTime + "</p>" + reminderTxtNum;
                                displayRoster.push({ html: workTime, holidays: holiday });
                                deferred.resolve(displayRoster, date);
                            } else {
                                if (self.diary.isPublicHoliday)
                                    workTime = self.diary.publicHolidayName;
                                // console.log('workTime=' + workTime);
                                deferred.resolve(workTime, null);
                            }
                        });
                    });
                });
                
            }, 1000);
            return deferred.promise;
        };

**Comment by gavinbarron** [comment]
You should inject the MaterialCalendarData service into your controller, and then you can make use of the setDayContent(date, content) function. This works by simply providing the date that you want to alter the content for and the new content.

**Comment by vnanhtuan** [comment]
Hi Gavinbarron,
I using MaterialCalendarData.setDayContent(date, content) to change content a day special but the system show error setDayContent undefined and MaterialCalendarData also undefined. Can you explain me why MaterialCalendarData undefined ?
This is my code:
- app.js file:
`var appProject = angular.module('appProject', ['ionic', 'ngMaterial', 'materialCalendar', 'ngRoute', 'LocalStorageModule', 'ui.tinymce', 'ui.uploader']);`
- my controller:
`app.controller('manageTakePhotoCtrl', ['$scope', '$http', '$rootScope', 'requestContext', '$q', '$filter', '$timeout', function ($scope, $http, $rootScope, requestContext, $q, $filter, $timeout, MaterialCalendarData) {
........
var today = new Date();
  $scope.setDayContent(today, '<span> :oD </span>')
......
})(angular, appProject);
`

Thanks you

**Comment by Alorse** [comment]
An example of how to inject?

**Comment by gavinbarron** [comment]
Take a look at the demo website code: https://github.com/jsmodules/angular-material-calendar/blob/master/website/js/demo.js

Injection to the controller about line 9 and usage around line 59

**Comment by gavinbarron** [comment]
Closing as I believe that we have resolved your issue. Re-open if needed
