### ISSUE TITLE
css class or style for days with events.

### ISSUE THREAD

**Issue by Alorse** [jsmodules/angular-material-calendar#57]
Hello,
It would be great to change the style of the days with events, so you can distinguish them better.

It happens that when you are using the calendar on mobile devices is difficult to display text in days, that would be nice to be able to distinguish a css class.

Thank you.

**Comment by gavinbarron** [comment]
That's a great idea! If you'd like to create an implementation and a PR we can certainly look at pulling it into the project

**Comment by fbertone** [comment]
I'm working on a PR.
At the moment I'm just adding a class to each day with an event in it, do you have any idea to further improve it?
