### ISSUE TITLE
Directive runs before JSON data is fetched.

### ISSUE THREAD

**Issue by BarkerLevi** [jsmodules/angular-material-calendar#58]
This may be due to my inexperience, but when I run the directive with JSON holiday data from a server it shows the holidays as undefined.  When I use the same exact data hard-coded it runs just fine.

`<calendar-md day-content=holiday.setDayContent></calendar-md>`

So, essentially this is running just before the HolidayService get function.  Is there a way to wait to run the directive until the JSON data is defined?

**Comment by gavinbarron** [comment]
The day-content attribute is used to set the callback function to set the content inside a given date.

In your case you likely want to have your setDayContent become promise aware and not return until you have loaded the data for the given day. it's a little hard to be more specific without an example. Perhaps a jsfiddle or codepen showing your issue and the code you're using?

**Comment by BarkerLevi** [comment]
I had been using 
```
var loadContentAsync = true;
    $log.info("setDayContent.async", loadContentAsync);
    $scope.setDayContent = function(date) {
        var key = [date.getFullYear(), numFmt(date.getMonth()+1), numFmt(date.getDate())].join("-");
        var data = (holidays[key]||[{ name: ""}])[0].name;
        if (loadContentAsync) {
            var deferred = $q.defer();
            $timeout(function() {
                deferred.resolve(data);
            });
            return deferred.promise;
        }
        return data;
    };
```
but I should have just used `MaterialCalendarData.setDayContent()`

**Comment by gavinbarron** [comment]
Thanks for the update @BarkerLevi
