### ISSUE TITLE
[Enhancement] Adding start and end date as parameters

### ISSUE THREAD

**Issue by sendilkumarn** [jsmodules/angular-material-calendar#60]
Currently there is no straightway to set start and end date in calendar. We can give two variables to set start and end date. 

I will submit a PR for this.

**Comment by gavinbarron** [comment]
Interesting use case. Essentially you would like to start and stop the calendar on an arbitrary day of the month if I understand what you're trying to do.

**Comment by sendilkumarn** [comment]
Yeah. In most of the date based elements we do have min date and max date functionality. Similar to that.
