### ISSUE TITLE
Changing height and width of a day of a month

### ISSUE THREAD

**Issue by famagusta** [jsmodules/angular-material-calendar#66]
How does one change the height and width of days in the month?

**Comment by gavinbarron** [comment]
The simplest way would be to change the height/width of the element that contains the calendar as the calendar will fill the space available to it.

**Comment by famagusta** [comment]
Thats what I ended up doing. But it would be nice to have some control over height/width of the day of months (or atleast each row of days). On small calendars,  events make some rows have more height han other days and it starts looking odd. 
Thanks for the advise.
