### ISSUE TITLE
Style/Directives inside day content don't work

### ISSUE THREAD

**Issue by diegodalbosco** [jsmodules/angular-material-calendar#75]
I tried to put a span with a css class in the content of some days but it desn't work. It's the same for others angular material directives. Maybe they need to be compiled?

**Comment by gavinbarron** [comment]
I've got a project where I have elements in the content of days that have
custom css classes that work just fine. Could you please provide a fiddle
or code pen illustrating your issue?

**Comment by diegodalbosco** [comment]
Now I resolved my problem using this directive [http://stackoverflow.com/questions/17417607/angular-ng-bind-html-and-directive-within-it](http://stackoverflow.com/questions/17417607/angular-ng-bind-html-and-directive-within-it). I used compile="" instead of ng-bind-html="" inside the md calendar js

**Comment by fbertone** [comment]
I've noticed the same: style attribute get removed from span.
However, in my case "class" attribute stays.
Maybe angular-material is doing some cleanup?

**Comment by diegodalbosco** [comment]
@fbertone I forked the repo and with a little fix I make it going. Try it if you want

**Comment by fbertone** [comment]
@diegodalbosco ok thanks

**Comment by gavinbarron** [comment]
if you have an improvement then please do submit a pull request

**Comment by gavinbarron** [comment]
@diegodalbosco can you please fix up your PR? It's not passing linting due to your choice of quotes

**Comment by diegodalbosco** [comment]
@gavinbarron I fixed it and now it passes the all checks
