### ISSUE TITLE
Self host icons can't be found 

### ISSUE THREAD

**Issue by AndriiDidkivsky** [jsmodules/angular-material-calendar#92]
Our source files used in sharepoint 2010 environment.
We have included  next file: 
"http://168.62.237.77/Style%20Library/Project-Dashboard/vendor/angular-material-calendar/angular-material-calendar.min.css"
"http://168.62.237.77/Style%20Library/Project-Dashboard/vendor/material-icons/material-icons.css"
"http://168.62.237.77/Style%20Library/Project-Dashboard/vendor/angular-material-calendar/angular-material-calendar.min.js"

Angular material, ect.
But we have got next warning  icon "$default:md-tabs-arrow not found". 
So, next/prev icons don't appear. 

Any workaround ? 

Thanks!

**Comment by gavinbarron** [comment]
Have you included the angular material style sheet? 
md-tabs-arrow is a directive from the angular material library upon which this module is built

**Comment by AndriiDidkivsky** [comment]
Of course, all required sources were included. Another libraries works fine, we create create our own md-icon and it will work. Issue has been got only with calendar.

**Comment by gavinbarron** [comment]
Seems weird. The svg that is being loaded there is baked into the angular-material.js file.

I'd double check your load order and version numbers

**Comment by AndriiDidkivsky** [comment]
this trouble has been got only with angular-material 1.1.0-rc5. 

If we use angular-material 1.0.8, problem will be resolved. 

But we use material with sharepoint this means that we need to support IE 10. Angular material less 1.1.0 has perfomance issue in IE. There are many issues on github https://github.com/angular/material/issues/8329

The IE Perfomance issue resolved with 1.1.0 version but movenext  icon doesn't appear  in the calendar. 

Angular-material 1.1.0-rc5 does not contain preloadIcons now. 

Any workarounds ?

**Comment by DEG-7** [comment]
i have the same problem, and i fixed adding this to my code
myApp.config(['$mdIconProvider', function($mdIconProvider) {
      $mdIconProvider.icon('md-tabs-arrow', 'lib/angularMaterialCalendar/tabs-arrow.svg', 48);
}]);
and i copied de svg of angular material src to my proyect lib

**Comment by AndriiDidkivsky** [comment]
reyazucar,  great. I'll try it tomorrow. I hope that you are right .
